name: mindquest
description: A Flutter mental health gamification app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  fl_chart: ^0.68.0
  lucide_icons: ^0.257.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  url_launcher: ^6.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  usage_stats: ^1.3.0
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  intl: ^0.18.1
  flutter_local_notifications: ^17.2.3
  confetti: ^0.7.0
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


